### ISSUE TITLE
RemoveMSI element doesn't work

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-DeployOffice#1009]
Please see the attached screenshot:

![image](https://user-images.githubusercontent.com/25488700/133880261-22806395-231e-4096-b8a0-c22131c4fa3d.png)

Office 2019 is installed, the 2021 XML file contains "RemoveMSI" line but the installation routine can't remove the old products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abccf87c-8c75-1dd7-929b-d59310979bf9
* Version Independent ID: 02e16bee-5591-0312-db88-4602f8872871
* Content: [Deploy Office LTSC 2021 - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/ltsc2021/deploy)
* Content Source: [DeployOffice/ltsc2021/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/ltsc2021/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
The Office 2019 products are not based on the legacy MSI installation technology, but rather use Click-to-Run. That's why the command to remove any MSI product does not catch the 2019 products. You can add a <Remove>-statement to your XML to uninstall C2R products. E.g. <Remove All="TRUE" /> to uninstall any C2R product before executing the <Add> portion of the XML.

**Comment by copenhaus** [comment]
ah, "<Remove All="TRUE" />" wasn't shown in the documentation...thanks...

**Comment by DHB-MSFT** [comment]
@copenhaus   We mention the Remove option in the "Remove existing versions of Office before installing Office LTSC 2021" section of the article:

_To uninstall 2019 versions of Office, Visio, or Project from the device, use the [Remove](https://docs.microsoft.com/en-us/deployoffice/office-deployment-tool-configuration-options#remove-element) element. You use the Remove element because 2019 versions of Office, Visio, and Project are installed by using Click-to-Run, not Windows Installer (MSI)._

We use RemoveMSI in the xml example in the article because we think most customers moving to Office LTSC 2021 will be coming from an MSI version of Office, such as Office 2013 or Office 2016.
