### ISSUE TITLE
Support-Matrix für Office-Konfigurationen veraltet

### ISSUE THREAD

**Issue by matthiaseckerle** [MicrosoftDocs/OfficeDocs-DeployOffice#1022]
Link to "Support-Matrix für Office-Konfigurationen" does link to an outdated document. Recent document should be this:
https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e85436-141e-3d54-7743-365fba243861
* Version Independent ID: c9afa702-9001-e0cb-3508-ab4b0d97cd46
* Content: [Windows Server end of support and Microsoft 365 Apps - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/endofsupport/windows-server-support)
* Content Source: [DeployOffice/endofsupport/windows-server-support.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/windows-server-support.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@matthiaseckerle   We're still working on resolving this issue. In the meantime, we've updated the URL for the matrix in our articles to point to the English version of the matrix (https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI). That's not ideal, but at least customers will be seeing the most current version of the matrix.

(It might take a few days for our localization process to pick up and implement this change to the URL in the articles.)

Once we get the issue resolved with the localized versions of the matrix, we'll go back to using fwlink 2111390 so that customers will once again be taken to the appropriate localized version of the matrix, where available.

Thanks again for bringing this issue to our attention.

**Comment by DHB-MSFT** [comment]
@matthiaseckerle  FYI, The marketing team (who is responsible for the matrix) has decided to only publish the matrix in English. The most current version (10 January 2023) is available here: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2OqRI. This is the URL we're using in our "end of support" articles.
