### ISSUE TITLE
Registry Settings for Microsoft 365 Apps for Business

### ISSUE THREAD

**Issue by stryqx** [MicrosoftDocs/OfficeDocs-DeployOffice#1056]
Please update this page with the registry settings needed to apply these changes for Microsoft 365 Apps for Business users.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5b380c-87db-3823-711d-6c8809392795
* Version Independent ID: cc5b380c-87db-3823-711d-6c8809392795
* Content: [Macros from the internet are blocked by default in Office  - Deploy Office](https://docs.microsoft.com/en-au/DeployOffice/security/internet-macros-blocked)
* Content Source: [DeployOffice/security/internet-macros-blocked.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/internet-macros-blocked.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@stryqx There are no registry keys available that are equivalent to the policy settings mentioned in the article. A benefit of this upcoming change to the default behavior is that it should help improve security in versions of Office that don't have access to policy settings. For versions of Office without access to policy settings, settings are available in the Office apps under **File** > **Options** > **Trust Center** > **Trust Center Settings...** > **Macro Settings**.

**Comment by ChrisNic817** [comment]
The biggest problem with this is the MoTW which is frequently not accurate (at least in the experiences of my users).  This MoTW appears even when they download files from their personal OneDrive or files from our internal servers.   Even though many of the files are not from the web or from locations that are used exclusively by the user (sharing outside the organization is disabled) just this tagging has caused support calls.  Even after teaching, because of the randomness of the occurrences, often the caller repeats to be trained once again.   The configuration of the Trust Center, having to add so many paths has caused a nightmare in management.   

If there are no registry settings for small environments where the GPOs are not used and the use of Cloud Policies doesn't seem to apply what are we supposed to do?   VBA has been a powerful tool and exploitable for so many years those that don't know about it disable it with the scary notifications and those that do know the rules and consequences.   Let's protect ourselves from ourselves.   Maybe it would be better to have a method to containerize a Macro file for malicious activity prevention, like not allowing calls outside the application to the OS directly or to use functions that interact with external applications not in the trusted interactions list (need to make one of these).

Just drives me nuts to have to go and release stuff all the time for users and explain stuff.   I even search for YouTube videos that can be shared just for these purposes to send to users that often need a refresher.

**Comment by kellieei** [comment]
Only enterprise editions of Office provide centralized management capabilities for organizations to manage Office, such as managing active content like macros and Trusted Locations. These tools can be helpful for designating locations for safe/known files and applying policy instead of relying on Trust Center settings that users can change. Because these additional management capabilities aren't available in business or home editions of Office, you need to rely on configuring the Trust Center settings in the Office apps. As you say VBA macros have been used by malicious actors to inflict damage, which is why we are changing the default for everyone to now block macros in files obtained from the internet. We understand change is challenging, and support calls may result in your organization. It is the goal with the “Learn more” button and article to educate and inform end users in unmanaged environments, so they can make an informed choice as to whether to proceed with removing MOTW and enabling macros from the internet.
