### ISSUE TITLE
Policy Check Interval not correct

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-DeployOffice#1075]
Unfortunately, this part is not true. "If the user is a member of an Azure AD group that is assigned a policy configuration, then the appropriate policy settings are applied and a check is made again in 90 minutes.". The policy check actually occurs roughly every 24 hours. The design may intend 90 minutes, but the service does not deliver it.

This is unfortunate because the Microsoft documentation indicates that the Microsoft 365 Apps admin center is the preferred place to implement policy. But, in practice, the policies are more limited and much slower to apply that Intune admin templates for Office.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa63a94-daaa-9491-213e-f0329f6299b1
* Version Independent ID: 47fe5a3a-ee7c-a7f7-b913-ca0ac3c063e0
* Content: [Overview of the Office cloud policy service for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/admincenter/overview-office-cloud-policy-service)
* Content Source: [DeployOffice/admincenter/overview-office-cloud-policy-service.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/admincenter/overview-office-cloud-policy-service.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by chhopkin** [comment]
Thank you for the feedback.  Here is some additional information that may help clarify the process.

The service includes a value in the response called CheckIn-Interval.  The client checks this value against the last check-in time, i.e. the time the client last asked for policies from the service.  There is another important value used in this decision which is the hash of the previous set of policies retuned to the client.  When the client calls the service, it provides the service with the hash value.  If the service determines that there are changes to sync since the last check-in (the client hash does not match the service hash) the service will return the full set of policies and a CheckIn-Interval value of 90 minutes.  If the service determines that there are no changes to sync since the last check-in (the client hash matches the service hash) the service will not return any policies and a CheckIn-interval of 0 will be returned which instructs the client to check back in 24 hrs.

**Comment by Air-Git** [comment]
Yes, that is what should happen. But in practice, after a change, the client does not check in for roughly 24 hours and so does not receive the changes. This is easily verified. If you delete the registry key HKCU\Software\Microsoft\Office\16.0\Common\CloudPolicy then the new settings will be applied instantly. But, if you do not, then the new settings will not be applied for roughly 24 hours. The service does not actually work as designed and documented.

**Comment by chhopkin** [comment]
That behavior is correct.  Take this scenario for example:

- At 10am the client calls the policy service and receives a response that indicates to the client that there are no policy changes since the last check-in and provides the client with the next check-in value which would be 24 hours.
- At 10:30am the same day the admin edits the policy configuration and configured some additional policies.
- After 10am the next day the client passes the 24 hour check-in interval and makes the call to the policy service.  The policy service returns the new set of policies as a change occurred since the client's last check-in.  The service provides the client with the next check-in value which would be 90 minutes.

The behavior to note in this scenario is the change that occurred to the configured policies.  When changes are made to policy configurations, the clients will not retrieve these changes until their check-in intervals pass and they call the service to request the changes.

I would argue that you are asking for a change to this behavior to introduce a way to signal the clients that policy configurations have changed and they should perform a check in as soon as possible?

**Comment by Air-Git** [comment]
You are absolutely correct that "If the service determines that there are no changes to sync since the last check-in (the client hash matches the service hash) the service will not return any policies and a CheckIn-interval of 0 will be returned which instructs the client to check back in 24 hrs." But that is not what the document says. It says that, if the user is a member of a group with a policy applied, it will check in every 90 minutes. The only case where the document says it will check in 24 hrs is the case where it is not a member of a group. In other words, it will NOT check every 90 minutes whether it has become a member of a group with a policy applied but, once a policy is applied, it will check every 90 minutes.

It would make no sense at all to drop the check in interval to 24 hours when no change is discovered, since the absence of a change is not a predictor of the absence of a future change. It would also be completely pointless to check in again in 90 minutes only after a change, since the occurrence of a change is not a predictor of a future change.

**Comment by DHB-MSFT** [comment]
@Air-Git  We'll update the article to clarify that the service won't check again for 24 hours if no changes were found during the most recent check. We appreciate you pointing out that issue with the documentation.

**Comment by Air-Git** [comment]
Thanks. It is a very strange design choice. The logical conclusion is that we need to keep updating the policy every 90 minutes, even with a null change, to get the clients to check in.

**Comment by DHB-MSFT** [comment]
@Air-Git   FYI, the article has been updated to clarify the timing of the checks. Thanks again for bringing this to our attention.

![image](https://user-images.githubusercontent.com/32883970/162341790-b99ac971-15a9-41fb-a626-2f963420488a.png)

**Comment by Air-Git** [comment]
Thanks! That's now completely clear. It is not what I would want, but it is clear.
