### ISSUE TITLE
To start the OCT, type setup.exe /admin on the command line?

### ISSUE THREAD

**Issue by colinxjoe** [MicrosoftDocs/OfficeDocs-DeployOffice#1144]
I Can't Start OCT?Why?

D:\OCT>setup.exe /admin

Office Deployment Tool

Setup [mode] [path]

Setup /download [path to configuration file]
Setup /configure [path to configuration file]
Setup /packager [path to configuration file] [output path]
Setup /customize [path to configuration file]
Setup /help

 /download Downloads files to create an Office installation source
 /configure Adds, removes, or configures an Office installation
 /packager Produces an Office App-V package from an Office installation source
 /customize Applies settings for Office applications
 /help Displays this message

And,,the link of download center in the Note (https://www.microsoft.com/en-us/download/details.aspx?id=49030), is just a Template.Where is current version of the OCT?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f16c547-1fea-d2e2-4c9c-08abac199219
* Version Independent ID: 5fd12aba-e56f-3551-26fe-c9e67686021b
* Content: [Office Customization Tool (OCT) 2016 Help Overview - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/oct/oct-2016-help-overview#feedback)
* Content Source: [DeployOffice/oct/oct-2016-help-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/oct/oct-2016-help-overview.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@colinxjoe  The Office Customization Tool comes with the Office 2016 (MSI) installation files. So you need to run "setup.exe /admin" from the folder where those files are located. 

The files up on the Microsoft Download Center (https://www.microsoft.com/download/details.aspx?id=49030) are the most current opax and opal files (look in the "Admin" folder from that download). The opax and opal files are what provide the choices you see in the Office Customization Tool wizard/tool. 

Although I don't think those files have changed much, if at all, since Office 2016 released. You should see an "Admin" folder where you have the Office 2016 (MSI) installation files. So you can copy the latest opax/opal files from the Download Center to your 2016 MSI install source.

Hope this helps.
