### ISSUE TITLE
Need step-by-step on updating Office 2019 in disconnected environments

### ISSUE THREAD

**Issue by robsmi-msfte** [MicrosoftDocs/OfficeDocs-DeployOffice#1158]
I need to know if this is the correct process:

- On a machine connected to the Internet, re-download the Office 2019 source installation files

- Transfer the entire Office 2019 source installation files to your disconnected network

- Copy the Office 2019 source installation files to a file share in your disconnected network.

- On a Windows device, click Add/Remove Programs and remove (uninstall) Office 2019

- On the same Windows device, location your folder that contains the "**Setup.exe" and configuration .XML**" file (which contains the name of the file share in your disconnected network), and run "**Setup /configure Office2019_Configuration.xml**".

Thanks,

Robert Smith
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f5cfe20-90ad-3f7e-8ae8-ff99bd1e1b55
* Version Independent ID: 97b2760a-50a2-f7c0-32ab-20b0420838d1
* Content: [Update Office 2019 (for IT Pros) - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/office2019/update)
* Content Source: [DeployOffice/office2019/update.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/update.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@robsmi-msfte  That would work, but there's a simpler solution that doesn't involve removing the already installed version of Office 2019. And will make future updates simpler.

Instead of the last 2 steps, you could do this instead:

- Make sure the devices with Office 2019 are configured to get updates from your local, disconnected file share. If you use Group Policy in your organization, you can use the "Update path" policy. If you don't use Group Policy, you can run the Office Deployment Tool in /configure mode on the devices with a simple xml file that just specifies the [UpdatePath attribute](https://learn.microsoft.com/deployoffice/office-deployment-tool-configuration-options#updatepath-attribute-part-of-updates-element) as your local file share.
- After you've changed the update path for the devices, you can manually check for updates by going to **File** > **Account** > **Update Options** > **Update Now**. That will force the Office update process to look at that share to see if an updated version of Office 2019 is available. Or you can just wait for the Office update process to naturally run, such as when the device reboots.
- In the future, when a new build of Office 2019 is released (usually on the 2nd Tuesday of each month), you would just need to use the ODT to download that build, and copy it over to your file share (replacing the previous version). Then, the next time the Office update process runs (or you manually force it to check), it should see there is a new version of Office 2019 to update to. 

All without having to uninstall Office 2019 each time. The Office update process is smart enough to compare what build is installed vs. what is up on the file share and recognize if it's a newer build and update to that newer build accordingly.

Hope that makes sense and helps.

**Comment by robsmi-msfte** [comment]
That makes perfect sense and does help.  I appreciate the feedback.
