### ISSUE TITLE
pls give a concrete example for semi annual with real version numbers 

### ISSUE THREAD

**Issue by Rika-Q** [MicrosoftDocs/OfficeDocs-DeployOffice#119]
it will be better to have a real life example of current version to expect in the next update,
there is a known issue on versions before 
https://support.microsoft.com/en-us/help/4025962/can-t-sign-in-after-update-to-office-2016-build-16-0-7967-on-windows-1
"Starting in Office Version 1805 (build 9330.2078), an updated version of ADAL 1.2.3 addresses some issues and has better logging capabilities. Please update to this version to test whether the issue is still occurring, and use this version or a later version to gather logs for support cases."
I"m still on version 1708 and having the issue - when can I expect to have at least version 1805 on a semi annual channel?

**Comment by DHB-MSFT** [comment]
Version 1808 is available in Semi-Annual Channel (Targeted) as of 11 September 2018. Version 1808 is expected to be available in Semi-Annual Channel in January 2019. See [Release information for updates to Office 365 ProPlus](https://docs.microsoft.com/officeupdates/release-notes-office365-proplus) for the latest versions/builds for each channel. Hope that helps.

**Comment by Rika-Q** [comment]
is the Version 1808 is expected to be available in Semi-Annual Channel in January 2019 for the semi-annual channel that today is on version 1708? as its confusing as I see two different semi-annual channels on the above url . sec q is while MS aware of such a major issue on versions before 1805, is there a fix that can be deploys to existing 1708 version or we really need to wait months until we get it?

**Comment by DHB-MSFT** [comment]
A new version of Semi-Annual Channel with updated features is released twice a year -- in January and July. Once a version is released to Semi-Annual Channel, it's supported for the next 14 months. That's why you see both 1803 and 1708 listed in that table. Both are supported (end of support date is listed in the last column of that table). This gives enterprises some flexibility in case they don't want move to the latest version of Semi-Annual Channel right away. See [Overview of update channels](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus) for more info about the update channels.  Version 1808 is expected to be available in January 2019, so if you update to Version 1808 at that time, the fix mentioned in that article will be included.

As for your 2nd question, there is a team that reviews all requested fixes for Semi-Annual Channel and determines whether to include that fix in Semi-Annual Channel. But, the fix needs to be deemed critical/essential to be approved, since enterprise customers using Semi-Annual Channel expect very little change in a released version of Semi-Annual Channel. 

Hope that helps. Thanks for your questions.
