### ISSUE TITLE
project pro 2016 volume license

### ISSUE THREAD

**Issue by crmedina** [MicrosoftDocs/OfficeDocs-DeployOffice#120]
I am unable to uninstall x86 project pro plus. I can install just fine. Here is my uninstall.xml file.
<Configuration>
    <Remove All="True">
        <Product ID="ProjectProXVolume">
            <Language ID="en-us" />
        </Product>
    </Remove>
</Configuration>

Here is my uninstall string - setup.exe /uninstall PrjPro /config uninstall.xml

I have also used 
config.xml
<Configuration>
	<Display Level="None" CompletionNotice="No" SuppressModal="Yes" AcceptEula="Yes" />
        <Setting Id="SETUP_REBOOT" Value="Never" />		
</Configuration>
uninstall string - setup.exe /uninstall PrjPro /config config.xml

**Comment by DHB-MSFT** [comment]
Did you use the Office Deployment Tool to install your volume licensed version of Project Professional 2016?  (I'm guessing that might be the case since you are referencing ProjectProXVolume in your xml file). If that's the case, then the appropriate command line to run with the Office Deployment Tool is setup.exe /configure uninstall.xml.  You don't need the other xml file. Hope that helps.

**Comment by crmedina** [comment]
Yes, I did. I just changed it in SCCM so we will see how it goes.

**Comment by crmedina** [comment]
If I use  setup.exe /configure uninstall.xml I get an error saying in need to use /config example setup.exe /config uninstall.xml which does not work .BTW the first one did not work either. Could something be corrupt? I know my x64 versions work fine but not my x86 for uninstalling Visio Pro 2016 and Project Pro 2016 both are volume license as well as the Office Pro Plus 2016(Volume) which works fine.

**Comment by DHB-MSFT** [comment]
Might be some confusion because there's 2 different setup.exe files.  There's the one that is the Office Deployment Tool, and there is the one that is part of an MSI installation of a volume licensed product. The command I gave you works with the Office Deployment Tool, and that should be able to remove anything you installed using the Office Deployment Tool (such as ProjectProXVolume).  If you installed using the MSI installation technology, you need to use the other setup.exe and the command line with all those other parameters. I don't think MSI version of Setup understands ProjectProXVolume designation. You'd have to use PrjPro as the Product ID.
