### ISSUE TITLE
How can I download office2019 volume license version?

### ISSUE THREAD

**Issue by niceysj** [MicrosoftDocs/OfficeDocs-DeployOffice#121]
Hi.
I can't download office 2019 perpetual license installation file.
My company is disconnected internet network.
We plan to download OFFICE 2019 files from Internet-enabled PCs, save them to file servers, and distribute them to the company.

This is my config and I type command that "setup /download download.xml"

<Configuration> 
  <Add SourcePath="\\192.168.0.3\SAC" OfficeClientEdition="32" DownloadPath="\\192.168.0.3\SAC"> 
    <Product ID="ProPlus2019Volume" > 
      <Language ID="en-us" />      
    </Product> 
  </Add> 
</Configuration>

I returned error Error Code : 30029-1007(0)

How can I download office 2019 installation file for volume license user?

**Comment by philipjbailey** [comment]
Hi 
I'm having a similar problem, the reason being that the VLC only has a server install version at this time.  We have to create our own CDN (Content Delivery Network) on our private network server.  The ODT (Office Delivery Tool) Is then instructed to download the Click-And-Run Installation file from the Server Share.  The VLC ISO is the Server Installation file and this is the case for both Office Pro-Plus 2019 and Office Standard 2019. 

The documents state there is an internet based ODT, but try as I might, I cannot find it anywhere on the internet generally (Google or Bing Searches) or by searching either Git-hub or Microsoft.com.

Can anybody point us to the internet based CDN?

**Comment by DHB-MSFT** [comment]
The Office Deployment Tool is available on the [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=49117).  You need the Office Deployment Tool because the Office 2019 installation files aren't available on the Volume Licensing Service Center. Then you create a configuration.xml file with the settings for what you want to download. Info about that is in the [Deploy Office 2019 article](https://docs.Microsoft.com/deployoffice/office2019/deploy).

@niceysj -- I can't see your config file, but you might want to look at this thread on the Answers forum about that error:  [https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365-mso_o365b/office-deployment-tool-error-code-30029-1007-0/47aa6b6d-e10d-4287-ae21-77ec21963126](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365-mso_o365b/office-deployment-tool-error-code-30029-1007-0/47aa6b6d-e10d-4287-ae21-77ec21963126)

Hope that helps.
