### ISSUE TITLE
What are the required versions of Outllok for Mac to connect to Exchange Online?

### ISSUE THREAD

**Issue by matthiasschroder** [MicrosoftDocs/OfficeDocs-DeployOffice#1219]
[Enter feedback here]

The blog post talks a lot about Outlooks for Windows, I would like to know what are the required versions of Outlook for Mac that allow connecting to Exchange Online today and after October 1st.

Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e86f8d4f-3eb1-6763-0f10-a0b637f3035c
* Version Independent ID: a6642647-dc4d-30a9-e962-76f7cd1f5089
* Content: [Office versions and connectivity to Microsoft 365 services - Deploy Office](https://learn.microsoft.com/en-us/deployoffice/endofsupport/microsoft-365-services-connectivity)
* Content Source: [DeployOffice/endofsupport/microsoft-365-services-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/endofsupport/microsoft-365-services-connectivity.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@matthiasschroder   Here is the support info for Mac versions connecting to Microsoft 365 services, such as Exchange Online:

- 2016: not supported (out of support since October 2020)
- 2019: supported until 10 October 2023
- LTSC 2021: supported until 13 October 2026
- Microsoft 365: supported as long as you're using a recent version

For 2019, LTSC 2021, and Microsoft 365, we recommend keeping up-to-date with the latest builds. For a list of recent builds, see [Update history for Office for Mac](https://learn.microsoft.com/officeupdates/update-history-office-for-mac).

If  you have specific questions related to the [New minimum Outlook for Windows version requirements for Microsoft 365](https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-minimum-outlook-for-windows-version-requirements-for/ba-p/2684142) blog post, you should post a question directly on that blog post.

Hope this info helps.

**Comment by matthiasschroder** [comment]
Hi,

thanks a lot for the reply. Is there a way to determine the version (2016, 2019, 2021) by the version number? I imagine that O 2019 can only be updated to a certain version, so everything below that version will be unsupported? 
Is it possible to get a definition of 'recent' wrt MS 365? The term is quite vague, it would be useful to know which versions are not supported or known not to work.

Best regards

**Comment by pbowden-msft** [comment]
@matthiasschroder (@DHB-MSFT)
Sure thing:
Build number 16.16 and below are Office 2016
Office 2019/2021/365 use a common build scheme of which 16.71 is the latest in the Current Channel. However, 2019 support will cease with build 16.78 in October.
As for the definition of ‘recent’ - a build released by us in the last 3 months is a good representation. So, today, recent would be 16.71, 16.70, and 16.69. 

I hope that helps!
