### ISSUE TITLE
Would love to see some more guidance / updates on Office 2019 patching in SCCM

### ISSUE THREAD

**Issue by SandyOCDA** [MicrosoftDocs/OfficeDocs-DeployOffice#124]
We're starting to deploy Office 2019 Professional to a few systems and want to manage updates in SCCM. I don't see the updates appearing in SCCM yet. Are we going to see some information on updating Office 2019 soon?

**Comment by DHB-MSFT** [comment]
I'm checking into this. Will get back to you when I find out more. Thanks.

**Comment by SandyOCDA** [comment]
Thanks Daniel!

Sent from my iPhone

On Oct 15, 2018, at 3:48 PM, Daniel H. Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm checking into this. Will get back to you when I find out more. Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-DeployOffice%2Fissues%2F124%23issuecomment-430040466&data=02%7C01%7Csandy.wood%40da.ocgov.com%7C75ffa81d13814693656e08d632f055f4%7Ce4449a56cd3d40baae3225a63deaab3b%7C0%7C0%7C636752405148471238&sdata=P%2F%2BvbjdXVOCGva2GfQ9H9xLWljW9BrA0T5mMlU1w0MI%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAkLpmh8bFthVbPxZG1TyP2FBk-q8l2Gdks5ulRCogaJpZM4XZr9_&data=02%7C01%7Csandy.wood%40da.ocgov.com%7C75ffa81d13814693656e08d632f055f4%7Ce4449a56cd3d40baae3225a63deaab3b%7C0%7C0%7C636752405148481507&sdata=M%2FO2LvJaBVqlLw5NP3ha87i%2BWBOSiK1hjxRKUl1vEIE%3D&reserved=0>.

________________________________

CONFIDENTIALITY NOTICE: This communication with its contents may contain confidential and/or legally privileged information. It is solely for the use of the intended recipient(s). Unauthorized interception, review, use or disclosure is prohibited and may violate applicable laws including the Electronic Communications Privacy Act. If you are not the intended recipient, please contact the sender and destroy all copies of the communication.

**Comment by DHB-MSFT** [comment]
@SandyOCDA -- the October updates for Office 2019 are up on the Microsoft Update Catalog -- [https://www.catalog.update.microsoft.com/Search.aspx?q=2019](https://www.catalog.update.microsoft.com/Search.aspx?q=2019).  (The fact that the October update says "Preview" is a known issue that will get fixed.). Also note Products = Office 365 Client, so you would need to select that in the Configuration Manager UI to get those updates to appear. In general, you can follow the same steps in this article -- [Manage updates to Office 365 ProPlus with System Center Configuration Manager](https://docs.microsoft.com/en-us/DeployOffice/manage-updates-to-office-365-proplus-with-system-center-configuration-manager). Even though the article is about Office 365 ProPlus, it's similar for volume licensed versions of Office 2019 since they both use Click-to-Run to manage updates. Be sure that OfficeMgmtCOM="True" in your configuration.xml file so that  Configuration Manager will manage the updates.  Hope that helps.  Thanks for the comment/feedback. We'll work on providing clearer guidance for this scenario.

**Comment by SandyOCDA** [comment]
Thanks a bunch for the great information! I do see what appears to be the October updates in my SCCM console that you mentioned:

(Preview) Office 2019 Perpetual Enterprise Client Update Version Perpetual for x86 based Edition 

I don't have the OfficeMgmtCOM="True" bit in my configuration.xml file but I will add it now. Is it acceptable to add it right after the Channel as in the example below?


<Configuration>
  <Add OfficeClientEdition="32" Channel="PerpetualVL2019" OfficeMgmtCOM="True">
    <Product ID="ProPlus2019Volume">
      <Language ID="en-us" />
	</Product>
    <Product ID="ProjectPro2019Volume">
      <Language ID="en-us" />
	</Product>
    <Product ID="VisioPro2019Volume">
      <Language ID="en-us" />
	</Product>
  </Add>  
  <RemoveMSI All="True" />
  <Display Level="None" AcceptEULA="TRUE" />  
</Configuration>

**Comment by DHB-MSFT** [comment]
@SandyOCDA  -- glad the info was helpful. Yes, you can add OfficeMgmtCOM="True" right after the channel as in the example in the article.  Note that the article also mentions that there is a Group Policy setting that you can use to configure this if you need to make the change to multiple devices.

**Comment by SandyOCDA** [comment]
I think Group Policy is the best for our situation. 

Thanks again for making our jobs infinitely easier.

**Comment by DHB-MSFT** [comment]
Glad we could be of assistance.
