### ISSUE TITLE
So exactly where is one supposed to source code for volume license key holders?

### ISSUE THREAD

**Issue by qwirk** [MicrosoftDocs/OfficeDocs-DeployOffice#126]
ARTICLE STATES"The installation files for Office 2019 are available on the Office Content Delivery Network (CDN) on the internet instead of on the Volume Licensing Service Center (VLSC). You can install Office 2019 directly from the Office CDN. Or, you can download the installation files from the Office CDN to a location on your local network, such as a shared folder, and install Office 2019 from that location. "

But the VLSC has code for Office 2109.  Found later it is just for web aps.  Did download project using setup and configuration file.  Source pointed to f:\, a nearly emply disk.. .so it was downloaded (I think) from the CDN.  When Project was opened, they PIDKEY was blank.  When I entered my Volume license key (which I paid for) it said it was the wrong key.  PLEASE ADDRESS the source for the code (the target too, where is a good default location for CAB files and how does the configuration xml point to this target, no documentation on setup parameters or its operation, I looked) and what compatible key works with each version of the code.  A MORE COMPLETE XML SHOWING INSTALL for a very small number of users (three) but with multiple products would be nice.  OR (and MSFT never does this) describe the architecture a bit more.  Thanks. Unhappy customer.  I pay the bills.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
All volume licensed versions of Office 2019, include Project and Visio, are available for download/installation from the Office Content Delivery Network (CDN).  To get download/install, you use the Office Deployment Tool and a configuration.xml file, which provides the settings for the download/install. Common things you'd need to set are listed here in the article -- [Edit the configuration.xml](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#edit-the-configurationxml), and there's a sample here -- [sample xml](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#sample-configurationxml-file-to-use-with-the-office-deployment-tool), There is additional setting info here -- [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool), although not all settings apply to Office 2019. There most common/relevant ones for Office 2019 are listed in the [Edit the configuration.xml](https://docs.microsoft.com/en-us/DeployOffice/office2019/deploy#edit-the-configurationxml) section. The SourcePath attribute can be used to specify where the Office 2019 installation files are download to from the Office CDN and/or where you do the install from (for example, install Office 2019 on a user's computer from a network share).

You only need to specify a PIDKEY if you're using MAK activation. If you're using MAK, you need to sign in to the [Volume Licensing Service Center](https://www.microsoft.com/licensing/servicecenter/default.aspx) to get your MAK key info for Office 2019.

Hope this information helps.

**Comment by qwirk** [comment]
I have read and done all of the above.  It is still failing.

Of course, all of this is a plot to have everyone outside a large corporation on the cloud... Given the security risks entailed in that, while it may enhance MSFT revenue in the short run, well once the holes in security are discovered... and or the Feds reinstitute your cozy relationship with Justice's' antitrust division (I know how that worked under IBM...) they may come to regret the decision.

In the meantime,  while I was able to download Project, it seems I got the wrong image (though I specified "ProjectStd2019" ) and the white installing office window never showed up it installed, but when I tried to enter the Volume MAK it said I had the wrong code:  All on the F: drive XML here:

<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <Add SourcePath="F:\" Channel="PerpetualVL2019">
    <Product ID="ProjectStd2019Volume" PIDKEY="NW7G3-Y3XWH-88X7Q-HH4F7-3J4W2">
      <Language ID="en-us" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" Channel="Monthly" />
  <Display Level="None" AcceptEULA="TRUE" />
  
</Configuration>

Office Pro XML Here:

<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <Add SourcePath="F:\ProPlus" OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="ProPlus2019Volume" PIDKEY="VBQD8-HNPC6-WJ4TG-DD9MH-4C33D">
      <Language ID="en-us" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" UpdatePath="&quot; &quot;" Channel="Monthly" />
  <Display Level="None" AcceptEULA="TRUE" />
  
</Configuration>

Both started from Powershell (admin) to cmd then from F:\setup.exe /download name.xml


                This ager a long time did work and did  create f:\ProPlus\Office/Data cabinet files.

But on execution of  F:\setup.exe /download name.xml  I got a flash of the OFFICE Install Window.. then nothing.


FROM YOU COMMENT BELOW... it says that VL versions are on CDN.  So, what "Source" should be specified or is it just the Produuct ID.  If I did have the proper version of Project, why didn't the MAK load?

Also, should any changes be made in the configuration.xml file between /download and /configure?

**Comment by bbacharz** [comment]
I am having a similar issue. I was able to install the 64-bit version of Office 2019 using ODT. I then had to roll back (my mistake, did not account for some items). I am now trying to install the 32-bit version and it keeps sticking on install. I get to about 10% and it stalls. I have tried the install multiple times and I have downloaded the cabinet files multiple times. No change in result. 

Below is my xml configuration. 
/Configuration>
  /Add SourcePath="C:" OfficeClientEdition="32" Channel="PerpetualVL2019">
      /Product ID="ProPlus2019Volume"  PIDKEY="AAAABBBBCCCCDDDD" >
         /Language ID="en-us" />
      //Product>
  //Add>
  /RemoveMSI All="False" />
  /Display Level="Full" AcceptEULA="TRUE" />  
//Configuration>

I have tried altering the RemoveMSI attribute back and forth as well.

**Comment by DHB-MSFT** [comment]
@bbacharz  -- For troubleshooting questions such as these, I'd recommend posting them to the [Answers forum](https://answers.microsoft.com/) or the Tech Community(https://techcommunity.microsoft.com/). More people are on those sites and you will probably get a faster response/answer. Or you can always contact [Microsoft Support](https://support.microsoft.com/contactus). 

BTW, RemoveMSI only works for MSI versions of Office. Office 2019 uses Click-to-Run, so that attribute isn't doing anything in this case.

Thanks.

**Comment by DHB-MSFT** [comment]
@qwirk -- [SourcePath](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#sourcepath-attribute-part-of-add-element) is used for 2 things. If you're downloading the files from the CDN, it's where the files will get downloaded to. If you're installing Office (using /configure) the SourcePath indicates where the install files are located. In many cases, you can use the same xml file for both /download and /configure.

In your xml file, you might want to set Display Level="Full" so that any error messages will appear to help you troubleshoot. At least while you're working out how to get things installed. Once you have that sorted out, you can change it to "None" if you're deploying to your users.

Also, when you use /download, all the Office 2019 products, including Office Professional Plus 2019, Visio, and Project are downloaded together. They're all contained in the stream.x86.x-none.dat or stream.x64.x-none-dat file, depending if it’s the 32-bit or 64-bit version of Office. So as long as your downloading 2019 and the right bit-ness, you're getting the right files and wouldn't be downloading the wrong "image."  

Hope that helps.

**Comment by RAJU2529** [comment]
hi bbacharz , uninstall the old office 64 bit version by using revo uninstaller

**Comment by qwirk** [comment]
Responding to DHB=MSFT and SourcePath.  I very much appreciate your documenting the use of SourcePath AND noting that multiple OFFICE products are downloaded at the same time.  I have not seen those two little nuggets in the standard documentation MSFT directs one to for Office 2019 install.  So THANKS.
  A question that arises from you answer, is can you move the /dat file to a standard net share instead of running setup twice?  (O course, the SourcePath would change to the share where the dat file would be located. )   If so, that also is not documented in the standard install docs.  They should be revised ASAP.

**Comment by DHB-MSFT** [comment]
@qwirk -- yes, the SourcePath can be a share on your network (it's mentioned in the [documentation about SourcePath](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#sourcepath-attribute-part-of-add-element)) and you would still only need one xml file. When you do setup /download the files will get downloaded from the Office Content Delivery Network (CDN) on the internet and be saved to your network share. Then, when you run setup /configure on the device you want to install Office on, the Office Deployment Tool (setup.exe) will look on the network share for the installation files.

I thought we mentioned that the .dat file contained multiple products somewhere in our documentation. I'll double-check and if we haven't, I'll get it added. Thanks for the comment/feedback.

**Comment by qwirk** [comment]
It would be great if the details about sourcepath and the procedure to do a  one time download of the .dat file in the "Deploy Office 2019 (for IT Pros) document.  Sometimes understanding the relevant details of parameters can be lost when just trying to get the job done.  Also, I had some very long path names.  Seems to work better at the drive letter or one level of folder.

**Comment by qwirk** [comment]
Also at the link for "Configuration Options..."

                It starts off with a discussion of the command file (setup.exe)  and parameter file (name.xml).  There should be a section up front explicitly stating Setup works in TWO MODES.  And, the mode is specified during execution by the presence of the .dat file or not.  Only buried in SourcePath details does it speak of the "download mode" .

Also, which of the parameters in the .xml file work in which mode is not explicitly stated.

**Comment by DHB-MSFT** [comment]
The information about the modes (like /download and /configure) is in the [Office Deployment Tool overview article](https://docs.microsoft.com/en-us/DeployOffice/overview-of-the-office-2016-deployment-tool). There's a link to that at the end of the 1st paragraph of the"configuration options" article.

Since the Office Deployment Tool and the xml options mostly work the same for both Office 365 ProPlus and Office 2019, we didn't want to duplicate the content where there was overlap. The options called out in the "deploy Office 2019" article were those options we thought had 2019-specific considerations that needed explaining.

Thanks for your comments/feedback to help us improve our documentation.
