### ISSUE TITLE
Document does not mention if we can continue to use Outlook 2007 even if the support for it has ended in October 2017

### ISSUE THREAD

**Issue by sidkhandai** [MicrosoftDocs/OfficeDocs-DeployOffice#140]
[This document does not mention if we can continue to use Outlook 2007 even if the support for it has ended in October 2017. Please note that we do understand the fact that it will not get updated with product issues and features.]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60388d66-91f6-0eb6-e857-d6663d170437
* Version Independent ID: 3af34a6f-4953-5e52-b79b-c1196dc7d8ab
* Content: [Office 2007 end of support roadmap](https://docs.microsoft.com/en-gb/deployoffice/office-2007-end-support-roadmap?redirectSourcePath=%252fen-gb%252farticle%252fOffice-2007-End-of-Life-roadmap-416c54d8-823c-4def-bb7a-6a9b14ef2745)
* Content Source: [DeployOffice/office-2007-end-support-roadmap.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-2007-end-support-roadmap.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
You can use any of the Office 2007 apps (Word, Excel, Outlook, etc) even though Office 2007 is no longer supported. But we strongly recommend against that since Office 2007 is no longer receiving security updates. Also keep in mind that Outlook 2007 isn't supported by Exchange Server 2016 or Exchange Server 2019.
