### ISSUE TITLE
Privacy policy located in different place 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#145]
In windows 10, privacy policy is located under 
User Configuration\Administrative Templates\Microsoft Office 2016\ Tools | Options | General | Service Options… \ Online Content.
i enabled online control options and service level options 

Please include  send personal information must be disabled in gpo, which is located under
User Configuration\Administrative Templates\Microsoft Office 2016\ Privacy\Trust Center.

Also CEIP located under User Configuration\Administrative Templates\Microsoft Office 2016\ Privacy\Trust Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047d2b74-e963-a006-cb74-29257c409647
* Version Independent ID: 4f274c79-18ae-2c36-19a3-cfb73d7e6cf3
* Content: [Privacy options in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/privacy-options-in-office?toc=/deployoffice/office2016/toc.json)
* Content Source: [DeployOffice/security/privacy-options-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/privacy-options-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
The paths listed in the article are for admins that are using Group Policy with Active Directory on Windows Server. That's why they include \Policies\ in the path. If you're editing the local policy on Windows 10 using the Local Group Policy Editor, \policies\ isn't included in the path.

Thanks for your suggestion about adding information about "Send personal information"
