### ISSUE TITLE
Actually i not enabled in gpo

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#152]
Sir , I  enabled  file block settings  in registry keys . I not enabled in GPO  , because its gives some un compatible , so tried in registry keys , and I found  the way  to modify it , 
I followed the site for  the information  opening files in protected way .

https://support.microsoft.com/en-in/help/922850/error-message-in-office-when-a-file-is-blocked-by-registry-policy-sett

Above site  does not given the registry settings but   I found myself and I aaded the tgis key
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\excel\Security\FileBlock
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\powerpoint\Security\FileBlock
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\word\Security\FileBlock

I have taken the backup of modified  registry settings , 
Sir Will you verify the settings  , whether I made mistake or not 

I will uploaded the settings  via  onedrive , here is the the link.
https://1drv.ms/u/s!AmZoRRusRV59lGvoMKt1JtuLvnXz

Thanking you sir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a4e1f6-c4a9-3d08-9dcc-ed54ad313fdd
* Version Independent ID: 0a915718-ae55-1248-8b7f-d68d259473bf
* Content: [Block specific file format types in Office 2016](https://docs.microsoft.com/en-us/deployoffice/security/block-specific-file-format-types-in-office)
* Content Source: [DeployOffice/security/block-specific-file-format-types-in-office.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/security/block-specific-file-format-types-in-office.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
We don't usually document registry keys when there is Group Policy setting that does the same thing, because using Group Policy is the recommended way to do this. For a question such as yours (asking to verify registry settings),  I suggest posting your question to the [Answers forum](https://answers.microsoft.com/) or the [Tech Community](https://techcommunity.microsoft.com/). More people are on those sites and someone there is likely to be able to answer your question.
