### ISSUE TITLE
change the version 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-DeployOffice#158]
for every release office  , version no is diffrent , so i would recommend the microsoft office  team , to change verion from 16.0 to 19.0  for office 2019 .
The folowing benefits are added Once  chnaged the version 
1. users can able  to install previous versions  of  office suites together with ofice 365
2.Users can use   both office 2016 and  office 2019 together  on same machine 
3. Users can  themselves can compare the features  while creating a document

Thanking you sirfor the information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40c96f3-1c97-b538-ef82-ffbf0eef204d
* Version Independent ID: 2d6883b5-1b5c-dc16-9999-17d0652bfa48
* Content: [Supported scenarios for installing different versions of Office, Project, and Visio on the same computer](https://docs.microsoft.com/en-in/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer)
* Content Source: [DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/install-different-office-visio-and-project-versions-on-the-same-computer.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
The product team responsible for this did consider changing the version number for the Office 2019 release, but there were other benefits for keeping with the 16.0 version number and that's why they decided to keep the version number at 16.0. Keep in mind that running multiple versions of the Office suite on the same computer is not recommended. Thanks for your comment/feedback.
