### ISSUE TITLE
Office2019 Aus language

### ISSUE THREAD

**Issue by ms2004** [MicrosoftDocs/OfficeDocs-DeployOffice#197]
Can someone please help me with configuration file to setup Australian Language for Office 2019 setup.

**Comment by DHB-MSFT** [comment]
@ms2004 -- There isn't a separate Australian install. You would install using en-us as the language. Then, I think you would use the Office Language Preferences dialog box to set English (Australian) as your default editing language.  See [Add an editing language or set language preferences in Office](https://support.office.com/article/663d9d94-ca99-4a0d-973e-7c4a6b8a827d
) for steps on how to do that.  I hope that helps.

**Comment by ms2004** [comment]
I use configuration file to deploy the office2019 for all of 200 machines. I can't go through this way for each of my users.

**Comment by DHB-MSFT** [comment]
It looks like you can configure this by using Group Policy. Look under User Configuration\Administrative Templates\Microsoft Office 2016\Language Preferences.

**Comment by DHB-MSFT** [comment]
@ms2004 -- looks like you could also use the [Office Customization Tool](https://config.office.com) to create your configuration.xml so that English (Australian) is set as the editing language. Look under the "Application preferences" section and then put Australia in the search box to find the correct setting to configure. Hope that helps.
