### ISSUE TITLE
Access 2019 Product ID 

### ISSUE THREAD

**Issue by ConfaLo** [MicrosoftDocs/OfficeDocs-DeployOffice#216]
Can't find the correct configuration parameters to install Access 2019 Volume license. The Office Customization Tool doesn't offer Access as an option

**Comment by DHB-MSFT** [comment]
You can find a list of supported product IDs here -- [Product IDs that are supported by the Office Deployment Tool](https://support.microsoft.com/en-us/help/2842297/product-ids-that-are-supported-by-the-office-deployment-tool-for-click), which is linked to from the [documentation about the configuration.xml settings](https://docs.microsoft.com/en-us/DeployOffice/configuration-options-for-the-office-2016-deployment-tool#product-element). 

The Office Customization Tool is focused on deploying the suites, not standalone Office applications, so that's why you don't see that option.

Hope this helps.

**Comment by ConfaLo** [comment]
Thank you, I was exactly looking for a product ID's list.

Starting from Office 2019 the OCT is the only method provided to install any application, but Microsoft didn't explain how to use it with standalone ones.
