### ISSUE TITLE
Product Activation - No installed product keys detected

### ISSUE THREAD

**Issue by Shreeingame** [MicrosoftDocs/OfficeDocs-DeployOffice#230]
We have installed 2019 VL host key in our KMS server. We used latest ODT version 16.0.11107.33602 from Dec 2018. With this latest version we need to use **PerpetualVL2019** but in Oct 2018 version it used to be **Perpetual2019**
After installing using the latest ODT version when we check the status using ospp.vbs /dstatus it always gives "No installed product keys detected". However once you open the application & close it then running ospp.vbs /dstatus gives right details 
License Name showing as Office 19, Office19VisioStd2019VL_KMS_Client_AE edition
**QUESTION 1**: Why do i need to open the application once to have the details shown properly as mentioned above
**QUESTION 2** : What is AE Edition? Though it is VL -KMS I am seeing this AE edition for the first time.

**Comment by Shreeingame** [comment]
Adding few more comments: 
I was able to install office 2019 from same office 365 proplus binaries that we had donwloaded to install office 365 proplus. I have been using the same source file for the installation.

**Comment by manoth-msft** [comment]
I can answer Q1: At least since Office 2010, we only perform the activation for Office during first launch to allow admins to build golden images and capture (sysprep) images. If we would perform the activation during installation, we would break such scenarios where an admin wants to build a golden image, capture it, multiply it and each individual user should perform their own activation.
