### ISSUE TITLE
Semi annual channel 1808 on Office Customisation Tool

### ISSUE THREAD

**Issue by Rish8** [MicrosoftDocs/OfficeDocs-DeployOffice#233]
When will the latest Office365 Pro Plus Semi Annual Channel 1808 10730.20264, be available to select as a version on the Office Customisation Tool?

**Comment by DHB-MSFT** [comment]
@Rish8  -- thanks for letting us know about this. We're investigating.

**Comment by Rish8** [comment]
@DHB-MSFT - thanks, keep me posted. Normally, should it appear on the Customisation Tool drop-down, as soon as Microsoft have released the build on every patch Tuesday?

**Comment by DHB-MSFT** [comment]
@Rish8  -- you should now be able to see Version 1808 of Semi-Annual Channel in the [Office Customization Tool](https://config.office.com). Again, thanks for bringing this to our attention. The engineering team is working to improve the process by which this information is made available to the Office Customization Tool, so that it is available sooner after a new version or build is released.

**Comment by Rish8** [comment]
@DHB-MSFT - thanks for resolving this so quickly, appreciate it.
