### ISSUE TITLE
How to update the local source?

### ISSUE THREAD

**Issue by EnoXirtaMinu** [MicrosoftDocs/OfficeDocs-DeployOffice#251]
This is great for existing devices and keeping them up to date, but how do we ensure that new devices are installed with the latest version / build immediately? I would imagine that the local source can be updated on a regular basis? Maybe even through scripting?

Regards, Erik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b9b246-4e5d-8a54-b093-c85d225f2f31
* Version Independent ID: 65a7aac7-44a1-0f99-d3c1-f45ab4dee1e7
* Content: [Deploy Office 365 ProPlus from a local source](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-from-a-local-source)
* Content Source: [DeployOffice/deploy-office-365-proplus-from-a-local-source.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-from-a-local-source.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by clintoj** [comment]
You want a bit of this... https://docs.microsoft.com/en-us/deployoffice/configure-update-settings-for-office-365-proplus
But mainly this.... https://blogs.technet.microsoft.com/office_resource_kit/2014/01/28/managing-updates-for-office-365-proplus-part-2/
James

**Comment by EnoXirtaMinu** [comment]
@clintoj Nice, mainly THAT indeed (-:

**Comment by clintoj** [comment]
ok, so all of those are missing something fairly key... for the Monthly or SACT updates you need to add 
Channel="Monthly"
Channel="Targeted"
otherwise it will only download the SAC release into update folders
needs to be added into the row
<Add SourcePath="\\path\C2R\Updates\MAC" OfficeClientEdition="64" Channel="Monthly">

**Comment by Eric-ITaaS** [comment]
when downloading using this command "\\server\share\O365\setup.exe /download \\server\share\O365\config-pilot-SACT.xml"
It doesn't put the files on the share, instead it downloads the install files to the location where the command was issue, for example c:\work. Is this expected? The documentation indicates that it will download to the share, but that doesn't happen.

**Comment by geokh** [comment]
Dear Friends :
when downloading using this command "\server\share\O365\setup.exe /download \server\share\O365\config-pilot-SACT.xml"
It doesn't put the files on the share, instead it downloads the install files to the location where the command was issue, for example c:\work. Is this expected? The documentation indicates that it will download to the share, but that doesn't happen.

why it is not fixed because its not clear ?

**Comment by manoth-msft** [comment]
@geokh Can you double-check if your config-pilot-SACT.xml contais the attribute "SourcePath" as called out in Step 3? If no sourcepath is set, it downloads to the working directory (as you experienced), if sourcepath is set, it should download to the location specified. Please doublecheck and report back
