### ISSUE TITLE
Office 2016 with Project Pro for O365

### ISSUE THREAD

**Issue by seanshan86** [MicrosoftDocs/OfficeDocs-DeployOffice#272]
We have purchased and deployed Office 2016 (standalone msi) to all our users. Recently we decided to move to Project Online for our Project Management. We tried to install the Project Pro for O365 and we were not able to. 

What are the work arounds for this? Moving to Office 365 is not an option

**Comment by RAJU2529** [comment]
@seanshan86 . Office 2016 keys and office  365 keys are different.  I think either only suite one can be installed windows 
uninstall office  2016 and buy office 365 keys through Microsoft store, 
and then download the installation file. install on windows and then activate

**Comment by manoth-msft** [comment]
Unfortunately you can't mix Office 2016 VL MSI and Project 365 as this is not a supported configuration. I will close this issue due to the time passed since it was opened. If there are still technical issues, please post to https://techcommunity.microsoft.com/t5/microsoft-365-apps-for/bd-p/Microsoft365Apps. For documentation issues, please open a new issue here in GitHub.
