### ISSUE TITLE
Note beginning: "Best practice: If you use Configuration Manager already, make sure you..."

### ISSUE THREAD

**Issue by tmurfet** [MicrosoftDocs/OfficeDocs-DeployOffice#384]
This note doesn't account for situations where the Microsoft Deployment Toolkit (MDT) is being used to create a reference image and then subsequently a deployment image for VDI purposes. In that case we want Office 365 Pro Plus to be a part of the reference image but not activate until the user initially signs in to their VDI solution. The note should mention that scenario so that we understand how it's supported. How is Shared Activation handled for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b314dc73-e63b-9712-a4b1-9171ad6b7e82
* Version Independent ID: d3b16d76-6883-4e52-9c32-4699379d40c8
* Content: [Plan your enterprise deployment of Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/plan-office-365-proplus#feedback)
* Content Source: [DeployOffice/plan-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/plan-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by baardhermansen** [comment]
Other documents states explicitly that when we install O365 as part of a reference image, no Office applications must be started (if any one of them is started, we must uninstall Office and reinstall in order to correct the error). 
Shared activation must be enabled in a VDI solution. How you choose to handle the shared activation depends on the VDI solution. Using Citrix with WEM, you could point to a specific folder where the shared activation is stored (you do that in the ODT wizard) and then add that folder to the sync process.
