### ISSUE TITLE
GPO and registry don't stop Teams auto-start

### ISSUE THREAD

**Issue by JaniceDeReese** [MicrosoftDocs/OfficeDocs-DeployOffice#392]
We've tested on several clean PCs with multiple versions of Office (yes, 1902) and the GPO doesn't prevent Teams from auto-starting on logon as advertised.  The only way we've been able to kill it is to remove it from HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run.

**Comment by DHB-MSFT** [comment]
@JaniceDeReese -- so I think the issue might be that Version 1902 of Semi-Annual Channel, which has support for the "auto start" policy setting/registry key, hasn't been released yet. It's scheduled to be released tomorrow (9 July), which is the first time Version 1902 will be available in Semi-Annual Channel.

We provided the info about Version 1902 for Semi-Annual Channel in advance since you have to set the policy setting/registry key in advance of the new installation or update.

There is a Version 1902 available, but that's in Semi-Annual Channel **_(Targeted)_**  and it doesn't yet support the "auto start" policy setting/registry key. The build of Version 1902 that's being released to Semi-Annual Channel **_(Targeted)_**  tomorrow (9 July) will support that policy setting/registry key.

We'll update the article tomorrow with the specific build information. Although it's likely to be Build 11328.20368.

Hope that helps. Sorry for any confusion that may have caused.

**Comment by JaniceDeReese** [comment]
Thank you for the information.  I specifically looked in the article for any mention of a build that the GPO applied to, and we even tested with the June Semi-annual (Targeted) build of 1902 that includes Teams for that reason.  Could this information be included next time there’s advance information about a feature that’s being released?  It’d save us a lot of time.  We’ll do more testing today once the July builds are released.  Thanks!

Kind regards,
Janice DeReese
Desktop Analyst | Chevron Phillips Chemical Company LP
10001 Six Pines Drive, L-337A | The Woodlands, TX 77380
O: 832.458.3473 | C: 832.257.4199 | dereejl@cpchem.com<mailto:dereejl@cpchem.com>

**Comment by DHB-MSFT** [comment]
@JaniceDeReese  -- thanks for the feedback and apologies again for the confusion.
