### ISSUE TITLE
OneNote for Windows 10 & Sharepoint Server

### ISSUE THREAD

**Issue by jonasnilsson86** [MicrosoftDocs/OfficeDocs-DeployOffice#450]
Hi,
I am having a hard time understanding the text "...Instead, OneNote for Windows 10 notebooks must be stored in the cloud. For example, in OneDrive for Business or SharePoint Online. SharePoint Server is also supported".

If OneNote for Windows 10 Notebooks must be stored in the cloud, how can they be stored on Sharepoint Server? Have you updated the functionality to include Sharepoint Server and not revised the rest of the text before stating that Sharepoint Server is supported?

If Sharepoint Server is supported, are there any limitations to be aware of?

Thanks, 

Jonas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2319f44f-09fc-2649-2667-58fa159e3151
* Version Independent ID: 0b6c5c52-edaa-436d-95dd-0943d0b0c303
* Content: [Deployment guide for OneNote](https://docs.microsoft.com/en-us/deployoffice/deployment-guide-onenote#feedback)
* Content Source: [DeployOffice/deployment-guide-onenote.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deployment-guide-onenote.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@jonasnilsson86 -- We're double-checking with our OneNote experts, but we think the intention of the SharePoint Server reference is that since you can't create or save notebooks on the local device with OneNote for Windows 10, you can store them in _either_ a cloud-based location (such as OneDrive for Business or SharePoint Online) _or_ an on-premises network-based location (such as SharePoint Server).  We understand why the current wording could be confusing. We'll try to rectify that after we get confirmation from our OneNote experts.  Thanks for your feedback/question.
