### ISSUE TITLE
Optional connected experiences default state

### ISSUE THREAD

**Issue by jevgenij-martynenko** [MicrosoftDocs/OfficeDocs-DeployOffice#457]
What is the default state (On/Off) of optional connected experiences?
Now it seems impossible to manage default state, but still let users decide if they want it or not.
For example, we want to have it off by default in our organization, but still allow users explicitly turn them on.
Can this scenario be covered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/privacy/manage-privacy-controls#feedback)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@jevgenij-martynenko -- Currently, there's no way to have optional connected experiences disabled to start with, but still allow users to go to File > Account > Account Privacy > Manage Settings and select the checkbox to enable them. We've sent your feedback to the product team responsible for this area so that they can determine whether this is something that can be implemented in the future.  

Keep in mind that if these optional connected experiences are disabled to start with, users will get an error message when they try to use the particular optional connected experiences, such as Insert Online Picture. This might cause users to call your support desk for help, even though many (if not all?) of the error messages tell the user to check their privacy settings, and some of the error messages have a direct link to those settings.

Thanks for your feedback/suggestion.
