### ISSUE TITLE
Office 2019 (Volume licensed Versions) will be Version 1808 forever?

### ISSUE THREAD

**Issue by Justin-Shi** [MicrosoftDocs/OfficeDocs-DeployOffice#493]
Hi Team,

I saw the notes from https://docs.microsoft.com/en-us/deployoffice/office2019/update:
Office 2019 doesn't receive new features. If you want to get new Office features on an on-going basis, you should consider moving to an Office 365 plan that includes Office.

With the update history from https://docs.microsoft.com/en-us/officeupdates/update-history-office-2019, may I say that Volume licensed versions of Office 2019 will be Version 1808 forever with some security/quality updates?

From the Microsoft Product life-cycle portal, I saw that Office 2019 will out of support at 2025, so seems it cannot be Version 1808 forever? So how it be updated to another version like 1902 or higher? And when? I tried to search many materials but find nothing. Am I missed anything in here?

Thanks
-Justin

**Comment by DHB-MSFT** [comment]
@Justin-Shi  -- yes, **_volume licensed_** versions of Office 2019 (such as Office Professional Plus 2019 and Office Standard 2019) will always be Version 1808. Only the build number (the #####.##### in the parentheses) will change over time, as security and quality updates are released, as seen in the [update history](https://docs.microsoft.com/officeupdates/update-history-office-2019#volume-licensed-versions-of-office-2019) article. 

After Office 2019 goes out of support in 2025, you will need to purchase & install a version of Office that is available & supported at that time. Since that's still 6 years away, we can't predict what versions of Office will be available at that time.

We hope that answers your question.  Thank you.

**Comment by Justin-Shi** [comment]
@DHB-MSFT Perfect answer. Thanks very much. That's what I want.
