### ISSUE TITLE
How do you troubleshoot the automatic update process?

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/OfficeDocs-DeployOffice#519]
Example: the device/user are on semi-annual channel, latest (not restricted to a particular version). The scheduled task for updates shows that it has run successfully, but it doesn't update anything. Closing all the Office applications and running the scheduled task manually shows success, but no update. But if you go into an Office application File &gt; Office Account &gt; Update Options &gt; Update Now, it immediately starts updating. Why is the scheduled task showing that it succeeded, but it doesn't update?

Thanks!
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2324f001-9c0f-8730-0326-747300a87b78
* Version Independent ID: 5123d9b2-e45b-180a-1431-852542e8a1db
* Content: [Overview of the update process for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-the-update-process-for-office-365-proplus#feedback)
* Content Source: [DeployOffice/overview-of-the-update-process-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-the-update-process-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by davguent** [comment]
Ryan, the exit code or result from task scheduler will simply show that it ran, no other verbosity is provided because the task is designed background item only.  Background updates using CDN can be subject to throttle restrictions for temporary period of time in which Microsoft can review telemetry ensuring highest quality before broad deployment at scale.  Once gate is removed, client will detect higher build applicable, download pieces needed into  C:\Program Files\Microsoft Office\Updates\Download\PackageFiles directory.  Once build is staged, you will start to see notifications etc. documented [here.](https://docs.microsoft.com/en-us/deployoffice/end-user-update-notifications-for-office-365-proplus).  In contrast, when you use the update now button from backstage it can bypass throttle as you are deemed a "seeker" and obtain latest build on CDN.  IT Pros can also control the version advertised to clients and ignore throttle by using GPO TargetVersion if they so choose.  One final possibility is scheduled task may be blocked by temporary “Discovery Period.” Generally, updates will not happen within the Discovery Period which can last up to 24 hours after initial installation or if update check has already executed. IT Pros may encounter this scenario during compressed time validation in lab scenarios.
