### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by NedVargar** [MicrosoftDocs/OfficeDocs-DeployOffice#564]
The link to download ODT points to a version older then what is listed.  The version that comes down is 16.0.12325.20276 from 1/7/2020.  Please update if available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fb57a0-9af1-8ade-5846-4a44c6e1a702
* Version Independent ID: 24c49cab-e850-df1f-5050-bac2c37c96bd
* Content: [Microsoft Search in Bing and Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/microsoft-search-bing#feedback)
* Content Source: [DeployOffice/microsoft-search-bing.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/microsoft-search-bing.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@NedVargar -- thanks for bringing that to our attention. This is an oddity of the way our build system handles updates to the Office Deployment Tool and then builds the package to distribute the Office Deployment Tool on the Microsoft Download Center. 16.0.12325.20276 is actually the most current version of the Office Deployment Tool. We'll update the documentation to use that version number to try to reduce the confusion. The engineering team is also working on some improvements to the build system so that this version oddity won't be an issue in the future.  Thanks again for your feedback to help make the documentation better.
