### ISSUE TITLE
Are you fucking retarded ???

### ISSUE THREAD

**Issue by BoredLuddite** [MicrosoftDocs/OfficeDocs-DeployOffice#575]
Seconded - whoever thought this was acceptable is veritably retarded. Overriding browser settings with an extension that blocks changes to the search engine and stops the extension from being removed from OTHER PEOPLES products is not going to win you any business (or friends).

Stop this shit !

**Comment by lawtonj404** [comment]
Your use of language doesn’t help, Microsoft  will just delete your post, it’s not helping anyone.

I agree it’s Absolute stupidity from Microsoft, this needs to be stopped. As users we have a right of choice, I do not choose bing because I personally prefer another search provider, this is a disgrace and will take weeks to resolve as many clients don’t have group policy.

**Comment by BoredLuddite** [comment]
Agreed. Assume I was somewhat pissed off as I had literally just finished reading the advice from Office365.

**Comment by lawtonj404** [comment]
I feel exactly the same with 3700 users but swearing on github won’t help us, conversation and discussion needs to be constructive if we wish to get the changes reversed. 

I’m the worst one here for swearing and don’t think I’m preaching, we all just need this halted until proper consultation has been sought.

**Comment by DHB-MSFT** [comment]
Thank you, @lawtonj404.  

While we appreciate feedback, please remember that comments are subject to the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Locking this conversation because of inappropriate language.
