### ISSUE TITLE
Erreur "The Readiness report has encoutered a problem that may result in unexpected behavior

### ISSUE THREAD

**Issue by clavillestime** [MicrosoftDocs/OfficeDocs-DeployOffice#59]
[Office-error.zip](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/files/2155767/Office-error.zip)

**Comment by DHB-MSFT** [comment]
I've passed this along to the team that works on the Readiness Toolkit.

**Comment by clavillestime** [comment]
Hello, the scans were run with Office 2007 or 2010 on PC Windows 7 or Windows 10

**Comment by clavillestime** [comment]
Command : ReadinessReportCreator.exe -mru -addinscan -output \\server\xxx -silent

**Comment by clavillestime** [comment]
[Log_424D48DB273C477D8346F592371DD96C202BE173955395BF97A25139AF65842C_073ECC59FE2F3F23C89E0558C87A8E5000D49793E4100B69483CB2DF52FE28B3.log](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/files/2159669/Log_424D48DB273C477D8346F592371DD96C202BE173955395BF97A25139AF65842C_073ECC59FE2F3F23C89E0558C87A8E5000D49793E4100B69483CB2DF52FE28B3.log)

**Comment by tomdoyle-msft** [comment]
The reason you are getting the error in the Excel report is because no VBA data was collected. 
This could be caused by a number of reasons:

1. The PC running the scan does not have any documents in the users most recently used documents list (e.g. Fresh install, no files we opened)
2. The Readiness Toolkit was not run in the context of the user (e.g. it was run under the system account).
