### ISSUE TITLE
Updating of SCCM source files from CDN?

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/OfficeDocs-DeployOffice#665]
Back in June 2019, it was mentioned that keeping source files automatically updated was in the works.  Any progress?  It seems we now have to do this manually for each new version so that new users are immediately current and that's too much effort, IMHO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5f04ea-0285-19f0-6c28-ed2b53ce83de
* Version Independent ID: a4630f18-7c9d-6a66-58b7-67f074001a79
* Content: [Deploy Office 365 ProPlus with Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/en-us/deployoffice/deploy-office-365-proplus-with-configuration-manager?source=docs#feedback)
* Content Source: [DeployOffice/deploy-office-365-proplus-with-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-office-365-proplus-with-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by davguent** [comment]
Couple of Options:
1. Turn off Office 365 Client Management, revert to default behavior where Office Automatic Updates 2.0 scheduled task keeps clients up-to-date.  Windows 10 enables Delivery Optimization (DO) by default where clients will share content peer to peer leveraging DO Cloud Service.  In the old days every client pulled content from CDN and now that we can leverage DO this is the story we're leading with customers. You can continue to deploy Office 365 ProPlus with SCCM an collect hardware inventory for reporting but defer to DO for updates.

Delivery Optimization and Office 365 ProPlus
https://docs.microsoft.com/en-us/deployoffice/delivery-optimization 

2. Keep Office 365 Client Management enabled and leverage ADR rules within SCCM to automatically download and deploy desired Version\build to collection.  This is reasonable to do for SAC and SAC-T.  For Monthly we recommend customers leverage option 1 since content changes so frequently.
