### ISSUE TITLE
Which has precedence: GPO or ODT?

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/OfficeDocs-DeployOffice#669]
If I have a GPO to set all PCs to "Semi-Annual" but I install via SCCM with a configuration.xml file that forces "Semi-Annual (Targeted)", which channel wins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cd85e3b-e780-457e-9502-856bc6315bca
* Version Independent ID: 416e351f-13c5-e951-ea81-1650910a7c25
* Content: [Overview of update channels for Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus#configure-the-update-channel-to-be-used-by-office-365-proplus)
* Content Source: [DeployOffice/overview-of-update-channels-for-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-update-channels-for-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Hi, the channel specified in the add section gets installed in the first place, regardless of GPO. If there is another channel set as update channel (in <update>-section in ODT or via GPO), the device will switch to this channel during next update cycle after install.

**Comment by manoth-msft** [comment]
Thanks for bringing this up. We are using this as an opportunity to look into our documentation and clarify what is overruling what.

**Comment by DHB-MSFT** [comment]
We do mention in 2 other articles that Group Policy takes precedence over xml settings, but we could make that clearer in other places.  

https://docs.microsoft.com/deployoffice/configuration-options-for-the-office-2016-deployment-tool#channel-attribute-part-of-updates-element

https://docs.microsoft.com/DeployOffice/configure-update-settings-for-office-365-proplus

Thanks for the question, @rejohnson76

**Comment by rejohnson76** [comment]
It’s very hard to granularly control especially if a computer gets in the wrong channel.  Using security groups or OUs to filter such GPOs doesn’t scale very well.  All I want to do is enforce the Semi-annual channel for the general population and Semi-annual (Targeted) for our Pilot users.  If a user installs O365 from the cloud somehow they usually end up in the Monthly channel so we need to be able to change it.  A GPO works very well for that but since we can’t apply that to all PCS, we need to find a way to target individual PCs.  If we use a security group to apply the policy, what happens when the computer is moved out and the GPO no longer applies?  Does the registry retain the settings or are they removed?

I’ve seen some posts about using SCCM compliance policies which might work well for me since I can control SCCM collections better than security groups or OUs, but I must admit I don’t understand exactly how to use compliance, yet.  Maybe Intune policies are a future solution.

Thanks for your help.  We’ll get it figured out someday.  The channel concept is a good one but management tools need to be developed to more easily maintain them.

-Russell

**Comment by davguent** [comment]
**If a user installs O365 from the cloud somehow, they usually end up in the Monthly channel so we need to be able to change it.**
The Office 365 Admin can login to portal.office.com and search for 'software download settings' and using this panel can hide or define default channel which aligns with your strategy when installing from portal.

**All I want to do is enforce the Semi-annual channel for the general population and Semi-annual (Targeted) for our Pilot users.** 
Since Office is a machine-based installation it can't directly follow the user per se.  For example, User A gets SAC at logon and User B gets SAC-T is not possible.  This does create complexity for you in targeting their machines rather than users. Often customers use different tools to solve the same problem.  Some use domain policy, OCPS (coming), re-running ODT and others use Configuration Item within SCCM to stamp desired registry information and have ability to enforce\report compliance on setting.

**If we use a security group to apply the policy, what happens when the computer is moved out and the GPO no longer applies?  Does the registry retain the settings or are they removed?**
Once the policy is no longer in scope, the registry key under policy hive will be removed.  The Office Automatic Updates 2.0 scheduled task will detect setting removal and then update the registry key UpdateChannel which is the "winner" defining channel assignment.  Important to note, there are some caveats about moving slow to fast or fast to slow document in blog and docs.

[How to manage Office 365 ProPlus Channels for IT Pros](https://techcommunity.microsoft.com/t5/office-365-blog/how-to-manage-office-365-proplus-channels-for-it-pros/ba-p/795813 )

[Change the Office 365 ProPlus update channel for devices in your organization](https://docs.microsoft.com/en-us/deployoffice/change-update-channels)
