### ISSUE TITLE
Device Based Activation information?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-DeployOffice#68]
I can't find anywhere on docs.microsoft.com information about Office 365 Device Based Activation. The best resource I can find is https://blogs.technet.microsoft.com/nzedu/2017/05/03/device-based-activation-for-office365-proplus-great-for-education/ Can some updated info be developed and added to deployment details here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b314dc73-e63b-9712-a4b1-9171ad6b7e82
* Version Independent ID: d3b16d76-6883-4e52-9c32-4699379d40c8
* Content: [Plan your enterprise deployment of Office 365 ProPlus](https://docs.microsoft.com/en-us/DeployOffice/plan-office-365-proplus)
* Content Source: [DeployOffice/plan-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/plan-office-365-proplus.md)
* Service: **o365-administration**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by DHB-MSFT** [comment]
Device based activation is only available in the US and only for EDU customers. That's why we don't cover it in our enterprise deployment content for Office 365 ProPlus that's on docs.microsoft.com. The blog post that you reference and [https://aka.ms/officedba](https://aka.ms/officedba) are probably your best resources for information about it.
