### ISSUE TITLE
Device requirements for the Office Cloud Policy Service

### ISSUE THREAD

**Issue by Thommykatz** [MicrosoftDocs/OfficeDocs-DeployOffice#685]
One of our customers gets errors for some users (about 1000 out of 100.000 members in the Security Group) - notification says "Your policy failed to apply to this device" - so what requirements besides the ones that are mentioned on the website need to be met ?

**Comment by chhopkin** [comment]
Typically that error means that the client has received policies from the service but the service did not receive an acknowledgement back from the client telling the service that policies were received and applied successfully.  This could be due to timing or internet connectivity.  If this continues to occur for specific users it would be best to contact support.
