### ISSUE TITLE
E3 O365Pro and Standalone Environment

### ISSUE THREAD

**Issue by laquino08** [MicrosoftDocs/OfficeDocs-DeployOffice#69]
I have a question, so if we need to install the stand alone office applications on a user's machine and provide a user with an E3 license, are there any conflicts, is there a violation on the licensing? Technically we are paying for both, sometimes, we have remote sites that multiple users are using one machine. We could install one of the user's proplus install, but if that person should be terminated or we need to reinstall we would have to get the password of that user or login with another E3 license personnel. This option seems a bit of a security risk and tedious just for a machine to have Office Applications.
Can we assign an E1 license and still have a machine with a standalone installation of office? Again, we are paying for the standalone license and we are paying for the E1 monthly subscription as well (it just doesn't come with the office installation option like E3 does). I just want to know the bases on this for an enterprise environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/overview-of-licensing-and-activation-in-office-365-proplus)
* Content Source: [DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-of-licensing-and-activation-in-office-365-proplus.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
You should always check with your Microsoft representative about licensing issues to make sure what you want to do is compliant with any licensing agreements.

Question: what do you mean by "stand alone Office"? 

For scenarios where multiple users are using the same computer, you can use shared computer activation. Different users can use the computer, and if they're licensed, they can use the Office install on that computer. For more info, see [Overview of shared computer activation for Office 365 ProPlus](https://docs.microsoft.com/DeployOffice/overview-of-shared-computer-activation-for-office-365-proplus). 

When a employee leaves, you can remove that person's license by going to Office 365 admin portal. You can also deactivate any installations they have on any computers. You do both of those by editing the user's account. If another user logins to that computer and starts an Office app, they should be prompted to activate Office (if you're not using shared computer activation on that computer).

Hope that helps.

**Comment by DHB-MSFT** [comment]
Standalone Office can mean different things to different people, so just wanted to check. I usually think of that as the perpetual or volume licensed versions of Office, which seems to be what you're referring to since you're referencing MAK keys. Since that's the case, my comments about shared computer activation and the Office 365 admin center are NOT applicable, since those only apply to subscription versions of Office, such as Office 365 ProPlus.


You can use a non-subscription/perpetual version of Office to access Office 365 services (that are provided with your E3 license). But keep in mind that starting in October 2020, if you're using a perpetual version of Office to access Office 365 service, that version of Office must be in mainstream support to continue to access Office 365 services. For more info, see [Office 365 system requirements changes for Office client connectivity](https://techcommunity.microsoft.com/t5/Office-365-Blog/Office-365-system-requirements-changes-for-Office-client/ba-p/62327).
