### ISSUE TITLE
Not clear whether you still manage an deploy SUGs or not

### ISSUE THREAD

**Issue by dbaldwin32** [MicrosoftDocs/OfficeDocs-DeployOffice#701]
It's not clear on this page whether you still build a Software Update Group (SUG) either with an ADR or manually and deploy it or whether the O365PP client downloads the updates automatically from it's Distribution Point via the CDN. I believe it is the latter. What confused me was the link in Requirements that takes you to the normal Software Updates process. Can you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44a78111-ae98-5b26-b349-3e62960f02c4
* Version Independent ID: 23052a9d-431b-1367-791f-ef2f137d4c47
* Content: [Manage updates to Office 365 ProPlus with Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/en-us/deployoffice/manage-office-365-proplus-updates-with-configuration-manager#feedback)
* Content Source: [DeployOffice/manage-office-365-proplus-updates-with-configuration-manager.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/manage-office-365-proplus-updates-with-configuration-manager.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by davguent** [comment]
Customers have a variety of options to choose from when updating Office 365 Client.  By default, Office relies on scheduled task Office Automatic Updates 2.0 to keep Office up-to-date.  Customers can leverage Windows platform technologies such as Delivery Optimization (DO) so content is shared among peers.  For SCCM customers, they can couple DO with SCCM Connected Cache which basically turns existing Distribution Points into dynamic cache hosts.  These approaches could be classified as 'hybrid'.  

Customers can also opt to turn on 'Office COM' which overrides default Office behavior so Office 365 Client only pulls updates from Distribution Points.  This can by turned on by 'Enable management of the Office 365 Client Agent setting', GPO  or including OfficeMgmtCom in Config.xml when installing product.  In this scenario, you can follow traditional SCCM workflow and use an ADR or manually populate SUG which includes desired Office 365 build\version.  SCCM IT pros can turn on Peer Cache features of SCCM to help with content sharing.

All of these approaches will work, its just that the first set of options are more dynamic allowing the client to pull content it needs regardless of architecture, channel etc. vs SCCM integrated model where IT Pro has to be intentional about what is downloaded and staged on DPs.
