### ISSUE TITLE
Stop rolling back updated clients

### ISSUE THREAD

**Issue by rimetree** [MicrosoftDocs/OfficeDocs-DeployOffice#71]
When a user installs a secondary Office click-to-run product, like Project or Visio, the entire collection of Office products on the computer are changed to match the version of the secondary product. So, if I have an up-to-date version of ProPlus installed, but install a Project 2016 client from SCCM or other local source that was downloaded months ago, my ProPlus installation will now be rolled back to the version from the Project install. Am I missing something? Thanks.

**Comment by DHB-MSFT** [comment]
Office, Project, and Visio need to be using the same core Office binaries, such as mso.dll. So when you're installing Project/Visio from a local source that's older than the current Office install, Click-to-Run (the installation technology/engine) needs to "downgrade" Office to the version of Project/Visio you're installing. Since you're installing from that local source, Click-to-Run presumes that's the version you want installed.

Depending on how you have updates configured, Office, Project, and Visio would probably get updated to the most current version again the next time Click-to-Run runs and looks for updates.

One way to avoid this "downgrade" scenario is to do installs directly from the Office Content Delivery Network (CDN) on the Internet, because the CDN always has the most current bits. If this isn't an option (for example, because of bandwidth constraints), you should keep your local source location up to date with the most current installation bits. Current version info is available in the [Release information for updates to Office 365 ProPlus](https://docs.microsoft.com/officeupdates/release-notes-office365-proplus) article. Versions in that article also apply to Office 365 versions of Project and Visio.

Hope that explanation helps.
