### ISSUE TITLE
using /configuration ***.xml just opens "usage" page

### ISSUE THREAD

**Issue by nikitap90** [MicrosoftDocs/OfficeDocs-DeployOffice#720]
I've tried a lot of diffetent configs and none of them works, even basic one https://imgur.com/qVfz3hz

**Comment by RAJU2529** [comment]
@nikitap90 . Which article are you trying to say.  Photo is not clear. I could not able to read the sentences in photo. So please take full clear screenshot and upload here only

**Comment by nikitap90** [comment]
@RAJU2529 
![qVfz3hz](https://user-images.githubusercontent.com/11288575/77853158-52492500-71eb-11ea-904b-5c3089d4bda1.png)

**Comment by RAJU2529** [comment]
@nikitap90 . Give me two days to test on my system. But I don't like to install office 365 but I try with office 2019.

**Comment by RAJU2529** [comment]
@nikitap90 . Your have configured the .XML  as wrong.
And entered commands are also wrong.

**Comment by nikitap90** [comment]
@RAJU2529 This xml is automatically downloaded when i start setup.exe normally
The command is one, i've found here https://docs.microsoft.com/en-us/deployoffice/overview-of-the-office-2016-deployment-tool
not /configure nor /configuration is working

**Comment by RAJU2529** [comment]
@nikitap90 . Those commands are not because,  after your reading I successfully downloaded office 2019 pro plus by manually configured by me. 
 Also I have already configured  files for you, for 64bit , 32bit.   Tomorrow I will upload here, you can download the file, then  see the commands, proceed further

**Comment by RAJU2529** [comment]
@nikitap90 .Here is the configuration file with setup 

[Office365.zip](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/files/4400835/Office365.zip)

**Comment by nikitap90** [comment]
@RAJU2529 Well, it worked! Thanks for your help. The problem was I didn't configure SourcePath in configuration file?

**Comment by manoth-msft** [comment]
@nikitap90 The issue was that your setup.exe was the still compressed download of the Office Dpeloyment Tool (look at the title of the window). You have to run the exe standalone first to decompress the Office Deployment Tool, then you can run the /configure or/download switch.

@jwhit-MSFT Can be closed

**Comment by RAJU2529** [comment]
user @nikitap90  is conformed issue is solved  by added source path, i was given the configuration
