### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/OfficeDocs-DeployOffice#760]
How does this work with MFA? Is the user prompted for MFA during the license check? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
* Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
* Content: [Overview of licensing and activation in Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-licensing-activation-microsoft-365-apps)
* Content Source: [DeployOffice/overview-licensing-activation-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-licensing-activation-microsoft-365-apps.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by tiherz** [comment]
What i experienced in my lab: MFA breaks SSO (the "legacy sso mechanism" which also works for non-hybrid-joined machines). The user has to perform an interactive login. But interactive login and activation will of course works with MFA enabled as Office ProPlus uses ADAL. The user will then be prompted to authenticate.

AAD-joined / hybrid-joined clients should login seamlessly and activate Office even mit MFA without prompting the user. This is due to the PRT (primary refresh token) containing an MFA claim. However, the lifetime and automatic refresh of this MFAclaim how often the user gets prompted for MFA when using an app like Office ProPlus is based on you specific configuration. Look here for further information: https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-primary-refresh-token#when-does-a-prt-get-an-mfa-claim

**Comment by MJP-MSFT** [comment]
> How does this work with MFA? Is the user prompted for MFA during the license check?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: f3c236da-c63a-f789-f1b6-7aeb41f16c1f
> * Version Independent ID: 35319bac-d94f-832c-ce79-41bffe5c8d25
> * Content: [Overview of licensing and activation in Microsoft 365 Apps](https://docs.microsoft.com/en-us/deployoffice/overview-licensing-activation-microsoft-365-apps)
> * Content Source: [DeployOffice/overview-licensing-activation-microsoft-365-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/overview-licensing-activation-microsoft-365-apps.md)
> * Service: **o365-proplus-itpro**
> * GitHub Login: @jwhit-MSFT
> * Microsoft Alias: **jwhit**

@BakkerJan 
There are q few factors that can come into play. The first one being which Office client are you using? If using legacy like 2013 you might need to enable ADAL.  If your using 2016 and WIndows 10 your device might be leaning on WAM which can cause issues with auth/activation. 

I would suggest testing the process on this [article ](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/disabling-adal-wam-not-recommended)and then open a premier support case to get your scenario isolated and mitigated.
