### ISSUE TITLE
Only UpdateChannel changes not CDNBaseUrl

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/OfficeDocs-DeployOffice#792]
OK, so using SCCM management, switched channel from SAC to SAC-T and the task changed only the UpdateChannel value in the registry, not the CDNBaseUrl. 

I then applied the new channel's updates and now Microsoft apps show SAC-T as their active channel.

BUT, in the registry, the CDNBaseUrl is till SAC although UpdateChannel is SAC-T.

Will this ever change? I believe ConfigMgr is looking into CDNBaseUrl and not UpdateChannel for its reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization](https://docs.microsoft.com/en-us/deployoffice/change-update-channels)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by davguent** [comment]
This is correct "by design" behavior.
Can you take a look at my blog posting where I was able to include more granular information.
https://techcommunity.microsoft.com/t5/office-365-blog/how-to-manage-office-365-proplus-channels-for-it-pros/ba-p/795813

Let me know if something is missing from there in terms of answering your question.
