### ISSUE TITLE
Office 365 is now Microsoft 365

### ISSUE THREAD

**Issue by NathanBrianRoberts** [MicrosoftDocs/OfficeDocs-DeployOffice#797]
You have used Office 365 rather then Micrsoft 365 within the article in the what is my options section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00d5cfb7-cf02-611b-db91-12b9375db973
* Version Independent ID: 1d5b1e5a-85b4-cd6e-d6bf-826e5d062ad7
* Content: [Office 2010 end of support roadmap](https://docs.microsoft.com/en-us/DeployOffice/office-2010-end-support-roadmap)
* Content Source: [DeployOffice/office-2010-end-support-roadmap.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office-2010-end-support-roadmap.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@NathanBrianRoberts -- There are still some enterprise plans that use the Office 365 naming, such as [Office 365 E3](https://www.microsoft.com/en-us/microsoft-365/business/office-365-enterprise-e3-business-software?rtc=1&activetab=pivot%3aoverviewtab) and [Office 365 E5](https://www.microsoft.com/en-us/microsoft-365/business/office-365-enterprise-e5-business-software?rtc=1&activetab=pivot%3aoverviewtab), which is why we've kept the Office 365 name in some places. And in those places we've also included a mention of the Microsoft 365 naming.

**Comment by NathanBrianRoberts** [comment]
@DHB-MSFT -- Alright, thanks for the reply :)

Stay Safe!
