### ISSUE TITLE
Ambiguous wording regarding current and monthly update channels and this feature

### ISSUE THREAD

**Issue by Dawnes** [MicrosoftDocs/OfficeDocs-DeployOffice#836]
"These privacy controls are included in Version 1908 or later of Semi-Annual Enterprise Channel (Preview) and Semi-Annual Enterprise Channel."

Does this mean Current and Monthly channels do not get this implemented?
I don't believe that is the case, but the wording is ambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e739e6d3-0e0b-776f-a32f-52ab22761d3a
* Version Independent ID: e4507b1d-8327-ad07-1ddc-2c95c65c87cd
* Content: [Overview of privacy controls for Microsoft 365 Apps for enterprise - Deploy Office](https://docs.microsoft.com/en-us/DeployOffice/privacy/overview-privacy-controls)
* Content Source: [DeployOffice/privacy/overview-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/overview-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Dawnes -- These privacy controls have been available in Current Channel since Version 1904. Version 1904 is mentioned earlier in the article (first sentence of the 2nd paragraph). The privacy controls are also available in Monthly Enterprise Channel since it was released in May 2020, starting with Version 2003.

We specifically called out Version 1908 for Semi-Annual Enterprise Channel (Preview) and Semi-Annual Enterprise Channel to make it clear which version of those update channels had the privacy controls, especially since there wasn't a Version 1904 for those update channels.

Hope that helps.

**Comment by Dawnes** [comment]
@DHB-MSFT -- Thanks, this helps! I fully understand your comment and it all makes sense now. That said, we had 4 people who couldn't agree on it earlier today. ;)

**Comment by DHB-MSFT** [comment]
@Dawnes -- Thanks for the feedback and apologies for causing confusion. We are currently working on improving how we provide the information about which products and versions have the privacy controls. We'll take your feedback into account as we make those improvements.
