### ISSUE TITLE
Clarification on "Change the update channel with Configuration Manager"

### ISSUE THREAD

**Issue by TeslaSysA** [MicrosoftDocs/OfficeDocs-DeployOffice#881]
The info block in this section indicates that it is unsupported to downgrade the channel while using ConfigMgr, but it does not indicate _why_. A few of us were trying to help another admin, putting our heads together to try and figure out why this wouldn't work and what the proper way to get it done was, aside from a full wipe of Office and reinstall. 

Searching the history of this page found [this older article](https://techcommunity.microsoft.com/t5/office-365-blog/how-to-manage-office-365-proplus-channels-for-it-pros/ba-p/795813) which explains _exactly_ why and what the resolution is. Can we update the info block to reflect the properly supported path to downgrade. As much as I love to be current, for some orgs its not feasible and a downgrade to SAC or something akin is a necessary evil.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23ac821-9cb8-8855-598f-d1327df04fac
* Version Independent ID: 78f2127a-0c6b-d236-a415-6215c582ce8b
* Content: [Change the Microsoft 365 Apps update channel for devices in your organization - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/change-update-channels#considerations-when-changing-channels)
* Content Source: [DeployOffice/change-update-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/change-update-channels.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @davguent
* Microsoft Alias: **davguent**

**Comment by davguent** [comment]
Adding @DHB-MSFT as I've left Office.  @TeslaSysA I'm glad my blog posting was able to provide some addition clarity.  A native Office rollback feature in ConfigMgr doesn't exist which is why the client will only move forward when build advertised is higher. (Feature requests to address this in ConfigMgr have been rejected)  However, Clients which use CDN for Updates will respect GPO and have capability to move forward and rollback providing the capability you need.  This is a scenario where leveraging CDN, possibly ConfigMgr for Connected Cache + Delivery Optimization for content sharing is option to consider.
