### ISSUE TITLE
Document Clarification Suggestion: change user /install?

### ISSUE THREAD

**Issue by mav-cloud** [MicrosoftDocs/OfficeDocs-DeployOffice#907]
-Install Microsoft 365 Apps on an RDS server-

this section above doesn't indicate whether or not the admin should change user /install to disable .ini file mapping before installing 365 Apps with ODT. AFAIK Office Click2Run does not rely on .ini file mapping but it would be a nice to have clarification in the Microsoft documentation as a confirmation from an official source.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/change-user
Please let me know your thoughts : )
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6da18a8b-9e96-0155-7b30-9c211070d793
* Version Independent ID: 5a7e610a-bfcb-d9cc-03f7-589d970128d9
* Content: [Deploy Microsoft 365 Apps by using Remote Desktop Services - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/deploy-microsoft-365-apps-remote-desktop-services)
* Content Source: [DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/deploy-microsoft-365-apps-remote-desktop-services.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by manoth-msft** [comment]
Our documentation focusses on listing what you have to do, rather then covering all the steps you should not do. Simply, because the later approach can never be complete. So in short, if the change user /install is not listed in the article, it is not required to perform on an RDS server. Is not listed > not required. Main reason is because Office does not rely on .ini files, so there is no need to redirect them. 

Hope this helps as a clarification.
