### ISSUE TITLE
OneDrive doesn't work with User Profile Disks

### ISSUE THREAD

**Issue by JoeRainero** [MicrosoftDocs/OfficeDocs-DeployOffice#91]
OneDrive isn't working with User Profile Disks (UPD).  Why?

**Comment by DHB-MSFT** [comment]
Thanks for your question. I'm trying to get some info about this from the OneDrive product team. I'll get back to you when I find out more.

**Comment by DHB-MSFT** [comment]
Check out the 3rd bullet point in [OneDrive for Business and VDI environments](https://docs.microsoft.com/en-us/deployoffice/rds-onedrive-business-vdi):  "Data that's written to the user profile must be saved to the local hard disk and be available without a network connection."  That's why OneDrive won't work with user profile disks.
