### ISSUE TITLE
Teams and MAU

### ISSUE THREAD

**Issue by BillWeidenborner** [MicrosoftDocs/OfficeDocs-DeployOffice#912]
Having Teams listed as being part of MAU is causing some confusion. Currently, Teams has its own auto-updater which is not part of MAU. Admins have been trying to manage updates through MAU and are confused.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e840a0-92ac-3ba4-75b3-01a154d67899
* Version Independent ID: 8f7fd243-8f3a-7d32-8433-03b8167aee6f
* Content: [Update Microsoft applications for Mac by using msupdate - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/mac/update-office-for-mac-using-msupdate?source=docs)
* Content Source: [DeployOffice/mac/update-office-for-mac-using-msupdate.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/mac/update-office-for-mac-using-msupdate.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by Dimehta** [comment]
Hi @BillWeidenborner , Teams does not get it's updates actively via MAU (currently), but is registered with MAU so that it has MAU as it's back-up updater, in the event that of a an update failure or problem with it's own updater. To avoid any confusion for the end user, MAU UI displays an app on the UI as an available update or under updated apps, only if that app has been updated through MAU in the last 90 days. So for all end users, Teams will not be visible on the MAU GUI until an update has happened. Admins should not attempt updating Teams via MAU.

**Comment by BillWeidenborner** [comment]
@Dimehta, I understand that Teams doesn't get its updates actively from MAU. I'm the PM for the Mac client. The problem is that it isn't clear in the documentation and Admins reading the doc are getting confused thinking that Teams is updated through MAU and thinking that they can use MAU to control those updates. If you could somehow provide a note in the doc that clarifies what you've explained above so Admins don't get confused in the future that would be helpful.

**Comment by BillWeidenborner** [comment]
@Dimehta just to be more specific-- it might be good to include the following note on the page:
"Admins should not attempt to update Teams via MAU."

**Comment by Dimehta** [comment]
Thanks for the clarification @BillWeidenborner , we will update the documentation right away !

**Comment by DHB-MSFT** [comment]
We've taken this discussion offline with Bill. Will update documentation accordingly after getting his feedback.
