### ISSUE TITLE
Overview of Office 2019 (for IT Pros) documentation page: additional info

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-DeployOffice#921]
https://docs.microsoft.com/en-us/deployoffice/office2019/overview 
.
On this page, in the "Additional Information" section.
Add list of applications in Office 2019 Professional: Access (Windows only), Excel, OneNote, Outlook, PowerPoint, Publisher (Windows only), Word.

Add "(Windows only)" qualifier to Pro Plus app list. 

add note that Office 2019 Pro Plus and Office 2019 Standard are only available through a volume license from an official "MS Partner" vendor.  Initial purchase on a volume license requires a minimum of 5 licenses (of any type). 

SEARCH MS PARTNER NETWORK
https://partner.microsoft.com/en-us/support 
https://www.microsoft.com/en-ca/microsoft-365/business/microsoft-office-volume-licensing-suites-comparison (2019 Standard, Pro Plus, Standard for Mac)

add at bottom 
"There isn't a 2019 version of OneNote. The last version in Office is 2016.  It can be installed alongside OneNote Windows 10 / UAP. "
Add link to appropriate onenote 2016 installer, ie
INSTALL ONENOTE 2016 
https://go.microsoft.com/fwlink/?linkid=2110341 
https://www.onenote.com/download?omkt=en-US  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 429245cd-ba7b-e9e0-4ac1-7983fff85380
* Version Independent ID: 2f15021f-84d1-9f33-9e00-4422dce1c84d
* Content: [Overview of Office 2019 (for IT Pros) - Deploy Office](https://docs.microsoft.com/en-us/deployoffice/office2019/overview)
* Content Source: [DeployOffice/office2019/overview.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/overview.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment]
@Ronsss Thanks for taking the time to provide suggestions/feedback. 

We've updated the article to try to make the Windows/macOS differences clearer. We've also added a link to [Compare suites available through volume licensing](https://www.microsoft.com/microsoft-365/business/microsoft-office-volume-licensing-suites-comparison). 

We already have a link to [Deployment guide for OneNote](https://docs.microsoft.com/deployoffice/deployment-guide-onenote), which is the article we want IT Pros/admins to read before making any OneNote installation decisions. So that's why we don't include a direct link to the OneNote installers in this article.

We tend not to provide specific details on how to purchase Office products, since that can vary by type of customer and country. And there are other Microsoft websites that can provide that information. Our content is primarily focused on helping customers deploy & manage Office products, after Office has been purchased.
