### ISSUE TITLE
How to check O365/Project/Visio subscription license info through command line?

### ISSUE THREAD

**Issue by Bolt10000** [MicrosoftDocs/OfficeDocs-DeployOffice#947]
As mentioned [here](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/946), we can't check O365 subscription license status with "ospp.vbs /dstatus".

So what's the alternative to get the subscription license info through the command line?

I've checked that if subscription license is there then it creates a file in,
`%localappdata%\Microsoft\Office\Licenses\5\11366380622108500016231342162113319422`
*filename changes...

But the issue is that I can't differentiate if it's a license for Project or Visio or O365

Please share if there is a solution to it through default command/Powershell, without installing any other software. I'm looking to only get limited info if the subscription license exists or not and if it exists then for which product it exists.

**Comment by MJP-MSFT** [comment]
@Bolt10000   Thank you for reaching out. The reason you're not seeing anything in the ospp.vbs response is because our latest versions of Office use a new licensing process. I am working on getting documentation created to walk through the changes and the process to check legacy ospp or the new process.  

Until the docs get created you need to download the Office Licensing Diagnostic - https://www.microsoft.com/en-us/download/details.aspx?id=55948

After downloaded and extracted there is a PS1 script titled vnextdiag.ps1  you need to run this in PowerShell and it will return an output similar to ospp.vbs with entitlements status and activation status of the applications.

**Comment by Bolt10000** [comment]
@MJP-MSFT Thanks a lot for the info and confirmation, Issue is now resolved.
